### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by ciprus0** [AlucardSB/Alucard-Selfbot-src#32]
I made a tutorial for this bot and I run into a lot of errors that are always fixable, but this one I can't seem to figure out. I had them reinstall python 3.8, install C++ build tools, redownload the zip file, extract the folder, put token in, do pip install -U discord.py, pip install -r requirements.txt, everything. Nothing seems to work. The error is this:

Traceback (most recent call last): 
File "Main.py", line 28, in <module> config = json.load(f)
File "C:\Users\Sakshi\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
return loads(fp.read(),
File "C:\Users\Sakshi\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
return _default_decoder_.decode(s)
File "C:\Users\Sakshi\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 357, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\Sakshi\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 2 column 74 (char 75)
RIP I don't want to, etcc

I'm not fully sure that this person did everything I told them to, but I am assuming they did. Just wondering what the actual fix is for this because I've just been guessing, and it's not really a straight forward error.

https://media.discordapp.net/attachments/720115740581036073/823427852481069077/unknown.png?width=1166&height=656

**Comment by Fweak** [comment]
Your config.json file is formatted incorrectly. I would advise u to check it at: [Json Validator](https://jsonformatter.curiousconcept.com)

**Comment by ciprus0** [comment]
Yea the person just deleted things in their config.json file that they shouldn't have.
